### PR TITLE
Add K-Epsilon Model with Standard Wall Function in Eulerian Framework

### PR DESCRIPTION
**Pull request by Yashmandaokar**
This PR introduces a K-Epsilon turbulence model with a standard wall function, developed within the Eulerian framework of the SPHinXsys codebase. 

New Files and Their Functions:
TurbulenceModel.h & TurbulenceModel.cpp:
These files contain the defination and implementation of the Standard K-Epsilon turbulence model. The model incorporates a standard wall function to handle cells adjacent to the wall.

rans_dynamics.hpp & rans_dynamics.cpp:
These files contain the defination and implementation necessary  for the turbulent viscous force and the force due to the turbulent kinetic energy (TKE) gradient computations. Both forces are essential components in the incompressible RANS momentum equation.

common_weakly_compressible_FVM_classes.h & common_weakly_compressible_FVM_classes.cpp:
These files contain implementation for calculating the acoustic time step size, viscous forces, and pressure forces from the fluid in Finite Volume Method (FVM).

### CODE REVIEW

**Comment by FengWang3119** [comment]
Could you please describe the function and meaning of each file, such as "rans_dynamics.h" "common_weakly_compressible_FVM_classes.cpp"...?
Basicaly, we are highly recommended not to modify the source library when developing our own module.

**Comment by Yashmandaokar** [comment]
The "common_weakly_compressible_FVM_classes.cpp" is excatly the same as the one in "test_2d_FVM_flow_around_cylinder".  I just copied the project structure of "test_2d_FVM_flow_around_cylinder" case.

**Comment by FengWang3119** [comment]
QQ_1727605801769
One thing we need to take care is that, currently for linux system, the requirement for coding is stricter. 
So when I try to run your code on my PC (linux), you can see these errors. 
Please note that these errors will occur when you finally upload this code to the main library due to the CI test.
Therefore, if you have time please correct these. 
Now I would turn to my windows machine to run the code and to see what I could do on this,

**Comment by Yashmandaokar** [comment]
Yes i will get it working for the Linux system as well. Thank you for the feedback.

**Pull request merged**
